name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Action 
          uses: actions/checkout@v5
        - name: list and read file
          run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md
        - name: Cowsay art work 
          run: cowsay -f dragon "Run for cover, I am dragon Mwww !" >> dragon.txt
        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md